# Ejercicios de Arrays y Matrices con NumPy

**Alumno**: Emiliano Palacios
**Materia: Aprendizaje Automatico
**Fecha:** 6/4/2026
En este notebook se resuelven ejercicios básicos de **Arrays y Matrices con NumPy**, utilizando Python en Jupyter Notebook.

In [30]:
import numpy as np

## Ejercicio 1
**Crear un array de 10 elementos con ceros.**

In [31]:
array_ceros = np.zeros(10)
print("Ejercicio 1:")
print(array_ceros)

Ejercicio 1:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Ejercicio 2
**Generar un array con los números del 1 al 20.**

In [32]:
array_1_20 = np.arange(1, 21)
print("Ejercicio 2:")
print(array_1_20)

Ejercicio 2:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Ejercicio 3
**Crear un array con los números pares del 2 al 50.**

In [33]:
array_pares = np.arange(2, 51, 2)
print("Ejercicio 3:")
print(array_pares)

Ejercicio 3:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


## Ejercicio 4
**Crear una matriz de 4x4 con valores aleatorios entre 0 y 1.**

In [34]:
matriz_aleatoria = np.random.rand(4, 4)
print("Ejercicio 4:")
print(matriz_aleatoria)

Ejercicio 4:
[[0.18951632 0.45685049 0.08584744 0.95212948]
 [0.78438721 0.06955451 0.78627451 0.62696752]
 [0.63880077 0.54614291 0.54295409 0.51616206]
 [0.23874337 0.35652617 0.54734918 0.46768173]]


## Ejercicio 5
**Crear una matriz de 4x4 con valores aleatorios entre 0 y 1.**

In [35]:
matriz_aleatoria = np.random.rand(4, 4)
print("Ejercicio 5:")
print(matriz_aleatoria)

Ejercicio 5:
[[0.68012798 0.35423452 0.00593839 0.77238143]
 [0.69488127 0.76719122 0.10794127 0.58177791]
 [0.86904617 0.51418354 0.23591059 0.63095975]
 [0.31854116 0.67484415 0.92826482 0.72193706]]


## Ejercicio 6
**Realizar la suma elemento a elemento de los arrays**  
`a = [1,2,3]` y `b = [4,5,6]`.

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b

print("Ejercicio 6:")
print("Array a:", a)
print("Array b:", b)
print("Suma elemento a elemento:", suma)

Ejercicio 6:
Array a: [1 2 3]
Array b: [4 5 6]
Suma elemento a elemento: [5 7 9]


## Ejercicio 7
**Multiplicar dos matrices 3x3 de enteros aleatorios entre 1 y 10.**

In [37]:
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

producto = np.dot(matriz1, matriz2)

print("Ejercicio 7:")
print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)
print("Producto de matrices:")
print(producto)

Ejercicio 7:
Matriz 1:
[[ 7  5 10]
 [ 7  9  6]
 [ 8  1  6]]
Matriz 2:
[[ 3 10  3]
 [ 7  6  3]
 [ 5  3  3]]
Producto de matrices:
[[106 130  66]
 [114 142  66]
 [ 61 104  45]]


## Ejercicio 8
**Crear un array de 15 valores aleatorios entre 1 y 100 e imprimir su máximo, mínimo y promedio.**

In [38]:
array_random = np.random.randint(1, 101, 15)

print("Ejercicio 8:")
print("Array:", array_random)
print("Máximo:", np.max(array_random))
print("Mínimo:", np.min(array_random))
print("Promedio:", np.mean(array_random))

Ejercicio 8:
Array: [66 24 97  4  2 75 47 81 71 52 78 51 32 76 30]
Máximo: 97
Mínimo: 2
Promedio: 52.4


## Ejercicio 9
**Generar una matriz 5x5 con valores del 1 al 25 y extraer su diagonal.**

In [39]:
matriz_1_25 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_1_25)

print("Ejercicio 9:")
print("Matriz:")
print(matriz_1_25)
print("Diagonal:")
print(diagonal)

Ejercicio 9:
Matriz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal:
[ 1  7 13 19 25]


## Ejercicio 10
**Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcular la suma de cada fila y cada columna.**


In [40]:
matriz_random = np.random.randint(1, 21, (5, 5))

suma_filas = np.sum(matriz_random, axis=1)
suma_columnas = np.sum(matriz_random, axis=0)

print("Ejercicio 10:")
print("Matriz:")
print(matriz_random)
print("Suma de cada fila:")
print(suma_filas)
print("Suma de cada columna:")
print(suma_columnas)

Ejercicio 10:
Matriz:
[[ 1  7 11  9  5]
 [ 9 12 15 13 11]
 [17 12 18 19 17]
 [19 19  7  9 19]
 [10 15  9  4  8]]
Suma de cada fila:
[33 60 83 73 46]
Suma de cada columna:
[56 65 60 54 60]
